from __future__ import annotations

from kol_search.backend.models import AcquisitionSource


SOURCES: tuple[AcquisitionSource, ...] = (
    AcquisitionSource(
        id="x_official",
        platform="x",
        name="X API",
        kind="official_api",
        status="primary",
        purposes=("trend_discovery", "content_discovery", "kol_discovery", "kol_tracking"),
        native_semantics=True,
        server_http=True,
        supports_incremental=True,
        storage_policy="Persist permitted normalized fields and metric snapshots under the X Developer Agreement.",
        constraints=("Pay-per-usage", "Recent search covers seven days", "Budget and rate-limit headers required"),
        recommendation="Primary X source for native trends, search, account identity, and watched-account timelines.",
    ),
    AcquisitionSource(
        id="getxapi",
        platform="x",
        name="GetXAPI",
        kind="data_provider",
        status="secondary",
        purposes=("trend_discovery", "content_discovery", "kol_discovery", "kol_tracking"),
        native_semantics=True,
        server_http=True,
        supports_incremental=True,
        storage_policy="Confirm vendor retention terms before storing raw payloads; retain normalized provider provenance and metric snapshots.",
        constraints=("Usage-based billing", "Third-party dependency", "Monitor balance, response fields, and availability"),
        recommendation="Current internal X read provider for trends, content, KOL discovery, and watched-account timelines.",
    ),
    AcquisitionSource(
        id="twitterapi_io",
        platform="x",
        name="TwitterAPI.io",
        kind="data_provider",
        status="secondary",
        purposes=("trend_discovery", "content_discovery", "kol_discovery", "kol_tracking"),
        native_semantics=True,
        server_http=True,
        supports_incremental=True,
        storage_policy="Confirm the vendor contract before retaining raw payloads; always retain provider provenance.",
        constraints=("Third-party dependency", "Cursor and field semantics may differ from X API", "Contract review required"),
        recommendation="HTTP fallback or coverage supplement behind the same provider contract.",
    ),
    AcquisitionSource(
        id="twscrape",
        platform="x",
        name="twscrape",
        kind="data_provider",
        status="conditional",
        purposes=("trend_discovery", "content_discovery", "kol_discovery", "kol_tracking"),
        native_semantics=True,
        server_http=True,
        supports_incremental=True,
        storage_policy="Keep account cookies only in backend secret storage; retain normalized results with provider provenance.",
        constraints=("Unofficial X web API", "Dedicated test account can be restricted", "Internal experimental use only"),
        recommendation="Internal, low-cost connector behind the adapter boundary; automatically fall back when unavailable.",
    ),
    AcquisitionSource(
        id="fxembed",
        platform="x",
        name="FxEmbed / FxTwitter",
        kind="data_provider",
        status="conditional",
        purposes=("trend_discovery", "content_discovery", "kol_tracking"),
        native_semantics=True,
        server_http=True,
        supports_incremental=False,
        storage_policy="Treat the public service as best-effort and retain only normalized records with source provenance.",
        constraints=("Unofficial public service", "No availability SLA", "Coverage and response shape may change"),
        recommendation="Credential-free emergency fallback, never the sole production data contract.",
    ),
    AcquisitionSource(
        id="web_search",
        platform="web",
        name="Web Search API",
        kind="web_search",
        status="secondary",
        purposes=("trend_discovery", "content_discovery", "kol_discovery"),
        native_semantics=False,
        server_http=True,
        supports_incremental=False,
        storage_policy="Persist citations and derived evidence only when the selected search provider terms allow it.",
        constraints=("Cannot prove platform-native rank", "Cannot verify complete timelines", "Indexing bias"),
        recommendation="Use for broad recall and corroboration, then verify native claims through a platform API.",
    ),
    AcquisitionSource(
        id="getdaytrends",
        platform="x",
        name="GetDayTrends",
        kind="website",
        status="not_for_ingestion",
        purposes=("trend_discovery",),
        native_semantics=False,
        server_http=True,
        supports_incremental=False,
        storage_policy="The published terms prohibit mass extraction, caching, saving, or transferring site information.",
        constraints=("No documented ingestion API", "Hourly observations can miss short trends", "Terms prohibit backend harvesting"),
        recommendation="Human reference only; do not connect it to the production ingestion pipeline.",
    ),
    AcquisitionSource(
        id="nitter",
        platform="x",
        name="Nitter",
        kind="website",
        status="not_for_ingestion",
        purposes=("content_discovery", "kol_tracking"),
        native_semantics=False,
        server_http=True,
        supports_incremental=False,
        storage_policy="Unofficial access path; do not use as a production data contract.",
        constraints=("Uses X unofficial APIs", "Instances require real account sessions", "Public instance availability is unstable"),
        recommendation="Do not use as a primary or fallback backend source.",
    ),
    AcquisitionSource(
        id="youtube_data_api",
        platform="youtube",
        name="YouTube Data API",
        kind="official_api",
        status="primary",
        purposes=("content_discovery", "kol_discovery", "kol_tracking"),
        native_semantics=True,
        server_http=True,
        supports_incremental=True,
        storage_policy="Follow YouTube API Services terms and refresh or delete stored data as required.",
        constraints=("Daily project quota", "Search is not a native global trend list", "Channel and video lookups should be batched"),
        recommendation="Primary YouTube source for video search, channel identity, statistics, and uploads.",
    ),
    AcquisitionSource(
        id="youtube_channel_feed",
        platform="youtube",
        name="YouTube channel feed",
        kind="feed",
        status="secondary",
        purposes=("kol_tracking",),
        native_semantics=True,
        server_http=True,
        supports_incremental=True,
        storage_policy="Store feed identifiers and timestamps; enrich metrics through the official API.",
        constraints=("Enrolled channels only", "No discovery ranking", "Limited metrics"),
        recommendation="Low-cost freshness signal for known channels, never the KOL discovery source.",
    ),
    AcquisitionSource(
        id="reddit_api",
        platform="reddit",
        name="Reddit API",
        kind="official_api",
        status="conditional",
        purposes=("content_discovery", "kol_discovery", "kol_tracking"),
        native_semantics=True,
        server_http=True,
        supports_incremental=True,
        storage_policy="Use only after application approval and under Reddit's current data terms.",
        constraints=("Devvit data access is installation-scoped", "Broader commercial access may require approval", "Do not rely on unauthenticated .json endpoints"),
        recommendation="Integrate only after confirming an approved server-side access path for the product use case.",
    ),
    AcquisitionSource(
        id="instagram_api",
        platform="instagram",
        name="Instagram API",
        kind="official_api",
        status="conditional",
        purposes=("kol_tracking",),
        native_semantics=True,
        server_http=True,
        supports_incremental=True,
        storage_policy="Use authorized professional-account data within Meta permission and retention rules.",
        constraints=("Professional accounts and OAuth permissions", "Not a broad public KOL discovery API", "App review may be required"),
        recommendation="Use for accounts that explicitly authorize the product; keep public discovery disabled otherwise.",
    ),
)
