set search_path = kol_search, public;

create table x_kol_domain_score_snapshots (
    id bigint generated by default as identity primary key,
    account_id text not null references x_accounts(id),
    domain_key text not null,
    domain_query text not null,
    score double precision not null check (score between 0 and 100),
    confidence text not null check (confidence in ('High', 'Medium', 'Low')),
    score_version text not null,
    components_json text not null default '[]',
    evidence_json text not null default '[]',
    observed_at text not null,
    unique (account_id, domain_key, observed_at)
);

create index idx_x_kol_domain_scores
    on x_kol_domain_score_snapshots(domain_key, observed_at desc, score desc);
