set search_path = kol_search, public;

create table automation_agents (
    id bigint generated by default as identity primary key,
    name text not null,
    platform_id text not null,
    native_account_id text not null,
    native_username text not null,
    reply_connection_id bigint not null unique references automation_platform_connections(id),
    publish_connection_id bigint not null unique references automation_platform_connections(id),
    status text not null default 'draft'
        check (status in ('draft', 'running', 'paused', 'auto_paused', 'archived')),
    current_config_version_id bigint,
    pause_reason text not null default '',
    last_scan_at text,
    next_scan_at text,
    scan_cursor text,
    consecutive_failures integer not null default 0,
    created_at text not null,
    updated_at text not null,
    unique (platform_id, native_account_id)
);
create index idx_automation_agents_status
    on automation_agents(status, next_scan_at, id);

create table automation_agent_config_versions (
    id bigint generated by default as identity primary key,
    agent_id bigint not null references automation_agents(id) on delete cascade,
    version integer not null,
    config_json text not null default '{}',
    created_by text not null,
    created_at text not null,
    unique (agent_id, version)
);
create index idx_automation_agent_configs
    on automation_agent_config_versions(agent_id, version desc);
alter table automation_agents add constraint fk_agent_current_config
    foreign key (current_config_version_id)
    references automation_agent_config_versions(id) on delete set null;

create table automation_agent_events (
    id bigint generated by default as identity primary key,
    agent_id bigint not null references automation_agents(id) on delete cascade,
    event_type text not null,
    severity text not null default 'info'
        check (severity in ('info', 'warning', 'critical')),
    title text not null default '',
    message text not null default '',
    payload_json text not null default '{}',
    created_at text not null
);
create index idx_automation_agent_events_timeline
    on automation_agent_events(agent_id, created_at desc, id desc);

create table automation_agent_commands (
    id bigint generated by default as identity primary key,
    agent_id bigint not null references automation_agents(id) on delete cascade,
    command_type text not null check (command_type in ('scan_now', 'post_now')),
    status text not null default 'queued'
        check (status in ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
    requested_by text not null,
    error text,
    created_at text not null,
    started_at text,
    finished_at text
);
create index idx_automation_agent_commands_queue
    on automation_agent_commands(status, created_at, id);

create table automation_action_metrics (
    action_id bigint not null references automation_actions(id) on delete cascade,
    window_hours integer not null check (window_hours in (24, 72)),
    metrics_json text not null default '{}',
    captured_at text not null,
    primary key (action_id, window_hours)
);

create table automation_agent_metric_snapshots (
    agent_id bigint not null references automation_agents(id) on delete cascade,
    captured_at text not null,
    followers_count bigint,
    metrics_json text not null default '{}',
    primary key (agent_id, captured_at)
);
create index idx_automation_agent_metric_snapshots
    on automation_agent_metric_snapshots(agent_id, captured_at desc);

create table automation_agent_runtime_status (
    worker_id text primary key,
    model_ready integer not null default 0 check (model_ready in (0, 1)),
    telegram_ready integer not null default 0 check (telegram_ready in (0, 1)),
    write_ready integer not null default 0 check (write_ready in (0, 1)),
    allowed_models_json text not null default '[]',
    config_error text,
    updated_at text not null
);

create table automation_agent_defaults (
    id integer primary key check (id = 1),
    config_json text not null default '{}',
    updated_at text not null
);

alter table automation_opportunities
    add column agent_id bigint references automation_agents(id) on delete set null;
alter table automation_opportunities
    add column agent_config_version_id bigint
        references automation_agent_config_versions(id) on delete set null;
alter table automation_actions
    add column agent_id bigint references automation_agents(id) on delete set null;
alter table automation_actions
    add column agent_config_version_id bigint
        references automation_agent_config_versions(id) on delete set null;
create index idx_automation_actions_agent_timeline
    on automation_actions(agent_id, created_at desc, id desc);

revoke all on automation_agents, automation_agent_config_versions,
    automation_agent_events, automation_agent_commands, automation_action_metrics,
    automation_agent_metric_snapshots, automation_agent_defaults from public, anon, authenticated;
revoke all on automation_agent_runtime_status from public, anon, authenticated;
grant all privileges on automation_agents, automation_agent_config_versions,
    automation_agent_events, automation_agent_commands, automation_action_metrics,
    automation_agent_metric_snapshots, automation_agent_defaults to postgres;
grant all privileges on automation_agent_runtime_status to postgres;
