-- KOL Growth OS uses a private schema and direct PostgreSQL connections.
-- It is intentionally not exposed through Supabase Data API/PostgREST.
create schema if not exists kol_search;
revoke all on schema kol_search from public;
grant usage, create on schema kol_search to postgres;
set search_path = kol_search, public;

create table automation_platform_connections (
    id bigint generated by default as identity primary key,
    platform_id text not null,
    connection_key text not null default 'default',
    display_name text not null default '',
    status text not null default 'disconnected'
        check (status in ('connected', 'degraded', 'disconnected', 'paused')),
    enabled integer not null default 1 check (enabled in (0, 1)),
    capabilities_json text not null default '[]',
    metadata_json text not null default '{}',
    consecutive_failures integer not null default 0 check (consecutive_failures >= 0),
    last_health_at text,
    last_health_error text,
    created_at text not null,
    updated_at text not null,
    unique (platform_id, connection_key)
);
create index idx_automation_connections_platform
    on automation_platform_connections(platform_id, enabled, status);

create table automation_jobs (
    id bigint generated by default as identity primary key,
    job_type text not null check (job_type in (
        'manual_discovery', 'discovery_refresh', 'signal_refresh',
        'dispatch_actions', 'refresh_outcomes'
    )),
    platform_id text not null,
    connection_id bigint references automation_platform_connections(id) on delete set null,
    status text not null default 'queued'
        check (status in ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
    priority integer not null default 50 check (priority between 0 and 100),
    progress integer not null default 0 check (progress between 0 and 100),
    phase text not null default 'queued',
    payload_json text not null default '{}',
    result_json text not null default '{}',
    idempotency_key text unique,
    attempts integer not null default 0 check (attempts >= 0),
    available_at text not null,
    locked_by text,
    locked_at text,
    started_at text,
    finished_at text,
    error text,
    created_at text not null,
    updated_at text not null
);
create index idx_automation_jobs_queue
    on automation_jobs(status, available_at, priority desc, id);
create index idx_automation_jobs_platform
    on automation_jobs(platform_id, status, created_at desc);

create table automation_opportunities (
    id bigint generated by default as identity primary key,
    platform_id text not null,
    opportunity_type text not null,
    native_object_type text not null,
    native_object_id text not null,
    status text not null default 'open'
        check (status in ('open', 'planned', 'dismissed', 'expired')),
    priority integer not null default 50 check (priority between 0 and 100),
    score double precision not null default 0 check (score between 0 and 100),
    title text not null default '',
    evidence_json text not null default '[]',
    payload_json text not null default '{}',
    idempotency_key text not null unique,
    expires_at text,
    created_at text not null,
    updated_at text not null
);
create index idx_automation_opportunities_queue
    on automation_opportunities(platform_id, status, priority desc, score desc, id);
create index idx_automation_opportunities_native
    on automation_opportunities(platform_id, native_object_type, native_object_id);

create table automation_actions (
    id bigint generated by default as identity primary key,
    opportunity_id bigint references automation_opportunities(id) on delete set null,
    platform_id text not null,
    connection_id bigint references automation_platform_connections(id) on delete set null,
    action_type text not null check (action_type in ('comment', 'dm', 'owned_post')),
    native_object_type text not null,
    native_object_id text not null,
    status text not null default 'proposed' check (status in (
        'proposed', 'needs_review', 'scheduled', 'executing', 'succeeded',
        'confirmation_required', 'failed', 'cancelled'
    )),
    draft text not null default '',
    final_text text,
    payload_json text not null default '{}',
    idempotency_key text not null unique,
    scheduled_at text,
    approved_by text,
    approved_at text,
    locked_by text,
    locked_at text,
    started_at text,
    finished_at text,
    external_id text,
    receipt_url text,
    receipt_json text not null default '{}',
    error text,
    created_at text not null,
    updated_at text not null
);
create index idx_automation_actions_queue
    on automation_actions(platform_id, status, scheduled_at, id);
create index idx_automation_actions_limits
    on automation_actions(connection_id, action_type, finished_at);

create table automation_policy_decisions (
    id bigint generated by default as identity primary key,
    opportunity_id bigint references automation_opportunities(id) on delete cascade,
    action_id bigint references automation_actions(id) on delete cascade,
    outcome text not null check (outcome in ('auto_execute', 'needs_review', 'rejected')),
    policy_version text not null,
    score double precision check (score is null or score between 0 and 100),
    rules_json text not null default '[]',
    explanation text not null default '',
    created_at text not null,
    check (
        (opportunity_id is not null and action_id is null) or
        (opportunity_id is null and action_id is not null)
    )
);
create index idx_automation_policy_opportunity
    on automation_policy_decisions(opportunity_id, created_at desc);
create index idx_automation_policy_action
    on automation_policy_decisions(action_id, created_at desc);

create table automation_channel_controls (
    control_key text primary key,
    scope text not null check (scope in ('global', 'platform', 'account', 'action_type')),
    platform_id text,
    connection_id bigint references automation_platform_connections(id) on delete cascade,
    action_type text check (action_type is null or action_type in ('comment', 'dm', 'owned_post')),
    state text not null default 'enabled' check (state in ('enabled', 'paused')),
    reason text not null default '',
    updated_by text not null,
    created_at text not null,
    updated_at text not null,
    check (
        (scope = 'global' and platform_id is null and connection_id is null and action_type is null) or
        (scope = 'platform' and platform_id is not null and connection_id is null and action_type is null) or
        (scope = 'account' and platform_id is not null and connection_id is not null and action_type is null) or
        (scope = 'action_type' and platform_id is null and connection_id is null and action_type is not null)
    )
);
create index idx_automation_controls_lookup
    on automation_channel_controls(scope, platform_id, connection_id, action_type, state);

create table automation_audit_events (
    id bigint generated by default as identity primary key,
    actor text not null,
    event_type text not null,
    object_type text not null,
    object_id text not null,
    platform_id text,
    payload_json text not null default '{}',
    created_at text not null
);
create index idx_automation_audit_object
    on automation_audit_events(object_type, object_id, created_at desc);
create index idx_automation_audit_platform
    on automation_audit_events(platform_id, created_at desc);

create table automation_brand_config (
    id integer primary key check (id = 1),
    brand_name text not null default '',
    description text not null default '',
    audience text not null default '',
    tone text not null default 'professional, concise, conversational',
    product_url text not null default '',
    platform_handles_json text not null default '{}',
    allowed_claims_json text not null default '[]',
    forbidden_terms_json text not null default '[]',
    approved_domains_json text not null default '[]',
    updated_at text not null
);

create table automation_account_quotas (
    connection_id bigint not null references automation_platform_connections(id) on delete cascade,
    action_type text not null check (action_type in ('comment', 'dm', 'owned_post')),
    hourly_limit integer not null check (hourly_limit >= 0),
    daily_limit integer not null check (daily_limit >= 0),
    cooldown_seconds integer not null default 0 check (cooldown_seconds >= 0),
    updated_at text not null,
    primary key (connection_id, action_type)
);

create table automation_conversations (
    platform_id text not null,
    native_conversation_id text not null,
    native_account_id text not null,
    state text not null check (state in ('valid', 'revoked')),
    evidence_json text not null default '{}',
    verified_by text not null,
    verified_at text not null,
    updated_at text not null,
    primary key (platform_id, native_conversation_id)
);
create index idx_automation_conversations_account
    on automation_conversations(platform_id, native_account_id, state);

create table automation_worker_heartbeats (
    worker_id text primary key,
    host_label text not null,
    version text not null default '',
    status text not null default 'online' check (status in ('online', 'stopping', 'offline')),
    started_at text not null,
    last_seen_at text not null,
    updated_at text not null
);
create index idx_automation_worker_heartbeats_seen
    on automation_worker_heartbeats(last_seen_at desc);

create table x_accounts (
    id text primary key,
    handle text not null,
    display_name text,
    bio text,
    followers_count bigint not null default 0,
    following_count bigint not null default 0,
    tweet_count bigint not null default 0,
    listed_count bigint not null default 0,
    verified integer not null default 0,
    protected integer not null default 0,
    disabled integer not null default 0,
    spam_risk double precision not null default 0,
    anomaly_signals_json text not null default '[]',
    created_at text,
    profile_url text,
    avatar_url text,
    source_provider text not null,
    captured_at text,
    updated_at text not null
);
create unique index idx_x_accounts_handle on x_accounts(lower(handle));

create table x_kols (
    account_id text primary key references x_accounts(id),
    status text not null default 'candidate',
    score double precision not null default 0,
    reasons_json text not null default '[]',
    last_qualified_at text,
    updated_at text not null
);
create index idx_x_kols_status_score on x_kols(status, score desc);

create table x_tweets (
    id text primary key,
    author_id text not null references x_accounts(id),
    author_handle text,
    text text not null,
    language text,
    created_at text,
    conversation_id text,
    in_reply_to_user_id text,
    reference_type text,
    referenced_tweet_id text,
    mentioned_usernames_json text not null default '[]',
    relevance_score double precision not null default 0,
    like_count bigint not null default 0,
    repost_count bigint not null default 0,
    reply_count bigint not null default 0,
    quote_count bigint not null default 0,
    bookmark_count bigint not null default 0,
    view_count bigint not null default 0,
    url text,
    source_provider text not null,
    captured_at text,
    updated_at text not null
);
create index idx_x_tweets_author_time on x_tweets(author_id, created_at);

create table x_tweet_metrics (
    tweet_id text not null references x_tweets(id),
    captured_at text not null,
    like_count bigint not null,
    repost_count bigint not null,
    reply_count bigint not null,
    quote_count bigint not null,
    bookmark_count bigint not null default 0,
    view_count bigint not null,
    primary key (tweet_id, captured_at)
);

create table x_discovery_evidence (
    id bigint generated by default as identity primary key,
    source_account_id text,
    target_account_id text not null,
    relation_type text not null,
    evidence text not null,
    evidence_url text,
    weight double precision not null default 0,
    observed_at text not null,
    unique (source_account_id, target_account_id, relation_type, evidence)
);

create table x_trends (
    id text not null,
    name text not null,
    rank integer not null default 0,
    post_count bigint not null default 0,
    url text,
    captured_at text not null,
    primary key (id, captured_at)
);
create index idx_x_trends_latest on x_trends(id, captured_at desc);

create table x_trend_tweets (
    trend_id text not null,
    trend_name text not null,
    trend_rank integer not null default 0,
    tweet_id text not null references x_tweets(id),
    first_seen_at text not null,
    last_seen_at text not null,
    primary key (trend_id, tweet_id)
);
create index idx_x_trend_tweets_recent on x_trend_tweets(last_seen_at desc, trend_rank asc);

create table xhs_users (
    id text primary key,
    nickname text not null,
    native_id_resolved integer not null default 1,
    bio text,
    followers_count bigint not null default 0,
    following_count bigint not null default 0,
    verified integer not null default 0,
    protected integer not null default 0,
    disabled integer not null default 0,
    spam_risk double precision not null default 0,
    anomaly_signals_json text not null default '[]',
    profile_url text,
    avatar_url text,
    source_provider text not null,
    captured_at text,
    updated_at text not null
);

create table xhs_kols (
    user_id text primary key references xhs_users(id),
    status text not null default 'candidate',
    score double precision not null default 0,
    reasons_json text not null default '[]',
    last_qualified_at text,
    updated_at text not null
);
create index idx_xhs_kols_status_score on xhs_kols(status, score desc);

create table xhs_notes (
    id text primary key,
    author_id text not null references xhs_users(id),
    note_type text not null default 'unknown',
    title text not null,
    body text not null,
    published_at text,
    like_count bigint not null default 0,
    comment_count bigint not null default 0,
    collect_count bigint not null default 0,
    view_count bigint not null default 0,
    relevance_score double precision not null default 0,
    note_url text,
    source_provider text not null,
    captured_at text,
    updated_at text not null
);
create index idx_xhs_notes_author_time on xhs_notes(author_id, published_at);

create table xhs_note_metrics (
    note_id text not null references xhs_notes(id),
    captured_at text not null,
    like_count bigint not null,
    comment_count bigint not null,
    collect_count bigint not null,
    view_count bigint not null,
    primary key (note_id, captured_at)
);

create table xhs_comments (
    id text primary key,
    note_id text not null references xhs_notes(id),
    author_id text not null,
    author_nickname text,
    body text not null,
    created_at text,
    like_count bigint not null default 0,
    reply_count bigint not null default 0,
    source_provider text not null,
    captured_at text,
    updated_at text not null
);
create index idx_xhs_comments_note_time on xhs_comments(note_id, created_at);

create table xhs_discovery_evidence (
    id bigint generated by default as identity primary key,
    source_user_id text,
    target_user_id text not null,
    relation_type text not null,
    evidence text not null,
    evidence_url text,
    weight double precision not null default 0,
    observed_at text not null,
    unique (source_user_id, target_user_id, relation_type, evidence)
);

create table xhs_trends (
    id text not null,
    name text not null,
    rank integer not null default 0,
    note_count bigint not null default 0,
    url text,
    captured_at text not null,
    primary key (id, captured_at)
);
create index idx_xhs_trends_latest on xhs_trends(id, captured_at desc);

revoke all on all tables in schema kol_search from public;
revoke all on all sequences in schema kol_search from public;
grant all privileges on all tables in schema kol_search to postgres;
grant all privileges on all sequences in schema kol_search to postgres;
